---
title: "Activities"
---


## July 2026
- In-person meeting to be held at Memorial University, July 27-29.

## June 2026
- We have continued to meet for the journal club. Please see the [ACCDMi-tools](https://github.com/ahurford/ACCDMi-tools/tree/main) repository.
- A. Hurford gave the Blundon Seminar and a Plenary lecture at the [Canadian Undergraduate Mathematics Conference](https://math.mcmaster.ca/6340-2/). These activities are related to the Modelling education theme. 

## May 2026
- [ACCDMi newsletter](https://ahurford.github.io/accdmi-website/may-2026-newsletter.html)
- A. Hurford visited M. Plank at the University of Canterbury in April.
- New publication: Anokye, F., M. WZ Li, S. Walker, and A. Hurford. 2026 [Quantifying SARS-CoV-2 Omicron variant spread and the impact of non-pharmaceutical interventions in Newfoundland and Labrador, Canada](https://doi.org/10.1371/journal.pcbi.1013562).PLoS Computational Biology.

## March 2025
- We are running the [macpan2 calibration working group](https://github.com/ahurford/macpan2-calibration-working-group/blob/main/README.md) on Wed March 4 and 11. Please email Amy Hurford if you would like to participate.

## February 2026
- [ACCDMi newsletter](https://ahurford.github.io/accdmi-website/feb-2026-newsletter.html)
- Congratulations to ACCDMi trainee [Dr. Joseph Baafi](https://github.com/jbaafi) for completing his PhD Biology on _Modelling the Impact of Seasonality and Climate Warming on Mosquito Population Dynamics: Insights for Vector Control Strategies_ at Memorial University. Congrats Joseph!

## January 2026
- A. Hurford gave presentations at U Montreal (St. Hyacinthye)/PHAC (> 40 participants including virtual audience), York University, and McMaster University.

## December 2025
-  ACCDMi symposium (online) to be held on Wednesday December 10. Details [here](https://ahurford.github.io/accdmi-website/dec-symposium.html)

## November 2025
- [ACCDMi newsletter](https://ahurford.github.io/accdmi-website/nov-2025-newsletter.html)

## October 2025
- [ACCDMi newsletter](https://ahurford.github.io/accdmi-website/oct-2025-newsletter.html)
-  A. Hurford and J. Mack avian influenza research trip.
-  Advertise 2026 ACCDMi scholarships. 

## September 2025  
-  Trainees invited to apply for an ACCDMi scholarship. [Details here](https://ahurford.github.io/accdmi-website/scholarship.html)
-  ACCDMi members meeting.  
-  ACCDMi trainee members added to website.
-  Launch website.
-  Create repository for modelling education resources.  