---
title: "ACCDMi Newsletter - February 2026"
---

- The ACCDMi symposium in December 2025 was highly successful. We had 12 speakers and the schedule is still available [here](https://ahurford.github.io/accdmi-website/dec-symposium.html) if you would like to remember what work ACCDMi members are doing. Thanks to everyone who participated and special thanks to Dr. Nicholas Ogden (Public Health Agency of Canada) for his keynote presentation.

- ACCDMi members should have received an email regarding the ACCDMi journal club. If you would like to suggest a reading, please do so on the google link. The aim of the journal club is to build our shared interests for a productive in-person meeting in the summer of 2026 (to be held in St. John's, NL). Once we have identified the readings we are most interested in, we will schedule a hybrid meeting for the first journal club meeting.

- ACCDMi has a logo! Please use the [logo](https://ahurford.github.io/accdmi-website/logo.html) for your ACCDMi-related presentations.

- We have some preprints/publications in the last couple of months, which have been added to the website. If you have any ACCDMi-related publications, I would like to list these on the website. Please email Amy Hurford with information on any relevant publications.

Thanks again for your support of ACCDMi!