---
title: "Atlantic Canada Center for Disease Ecology Modelling"
format: html
---

The Atlantic Canada Center for Disease Ecology Modelling (ACCDMi) is a multidisciplinary research initiative to advance the science and application of infectious disease modelling to improve human and animal health.

ACCDMi will support the visibility of Atlantic Canada’s expertise in infectious disease modelling so that stakeholders, public health professionals, and experts in adjacent disciplines can discover the substantial expertise of mathematicians and statisticians and engage our experts in applied problems.

ACCDMi programs will build relationships and capacity through training, outreach, and collaborative partnerships to improve analyses by incorporating efficient algorithms, modelling approaches, and the perspectives of applied mathematics and statistics.

# News
- We need a logo! You are a graphic designer and a student at Memorial University, Dalhousie, Mount Allison, or the University of Prince Edward Island please consider applying desing our logo. Expressions of interest are due by September 19. Details here.
