---
title: "ACCDMi in-person meeting"
---

## Details

Date: Monday July 27 - Wednesday July 29.

Location: [Core Science Facility (CSF)](https://www.google.com/maps/place/Core+Sciences+Facility/@47.5730076,-52.7352078,17z/data=!4m6!3m5!1s0x4b0ca38f11772ad9:0x86dc564a03595279!8m2!3d47.5723779!4d-52.7368976!16s%2Fg%2F11cnphn4qd?entry=ttu&g_ep=EgoyMDI2MDcxMy4wIKXMDSoASAFQAw%3D%3D), Memorial University and online (email ahurford@mun.ca for details)

We will first meet in the Cater Andrews Room, CSF 2342. This is on the second floor to the righthand side of the whale skeleton's head. The whale's name is Altum. We will have the small group sessions in nearby rooms in CSF.

## Participants

### On site

| | | |
|:---|:---|:---|
| Sumit Jyoti | JC Loredo-Osti | Binod Shrestha |
| Amy Hurford | Abdou Fofana | Maheru Rahman |
| Chunhua Ou | Jingyu Li | Joshua Mack |
| Danhan Hu | Yuan Yuan | Francis Anokye |

### Online

| | | |
|:---|:---|:---|
| Edward Susko | Abdelmonem Mohamed | Guanjie Lyu |
| James Watmough | Ahsan Raquib | |

## Meeting activities

To begin each day Amy Hurford will give a 30 minute overview of what we hope to achieve during the in-person meeting/topics we should learn more about. The meeting with be a combination of talks, small group collaborative activities, and talks reporting back the work completed in small groups.  

### Talks

All participants are invited to give a 5-10 min _lightening talk_ about their research to introduce themselves to the group. This will be scheduled for all the participants listed above unless you email Amy Hurford to indicate you would like to opt out. You we welcome to use slides or not.

Anyone who has research/expertise that is valuable to ACCDMi's future directions is welcome to give a 30 minute talk on this. As an example, Abdou Fofana could give a talk on AI4PH and its relevancy for ACCDMi's future directions. Please email Amy Hurford if you are willing to give a 30 min research talk during the meeting.

### Small group collaborations

Small group collaborations will occur in parallel and you can choose to work on the activities that you fit your interests. There will be documents on the Google drive where the small groups should document their work (link will be shared by email only). Small groups can set up video-conferencing on their own to facilitate collaboration with off-site participants.

The activities below are divided into principal investigators and trainees. Principal investigators are faculty who have status to be participants on grants. Postdoctoral fellows can choose to work with the Principal investigator or trainee group.

Please complete the small group sign-up document (shared by email) prior to the start of the meeting. Every participant should sign-up for at least one activity and you are welcome to sign-up for multiple.

### Principal investigator activities

1. Review website for missing deliverables that have been completed in year 1.
2. Define directions of ACCDMi for year 2.
3. Work on any of the 4 grant proposals that ACCDMi is submitting in the next 2 months.

### Trainee activities

1. Compile an annotated bibliography of references that can be used to cite the value of ACCDMi or should be read by ACCDMi to advance our research.
2. Begin the R coding of an online Modelling education website that can host videos and administer quizzes hosted on github.
3. Work on the SGNN or other figures that are appropriate for grants.
4. Compile data that could be used to make graphs for use in grants.
5. Establish a collaborative project with another group member.
6. Update the [ACCDMi-tools](https://github.com/ahurford/ACCDMi-tools) github repository.

## Schedule

Activities and times refer to Newfoundland Time (NDT). Meetings occur in Cater Andrews (CSF 2342) and nearby breakout rooms.

() indicates the small group activity that Amy Hurford will be working on during this time.

### Day 1: Monday, July 27

| Time | Session |
|:---|:---|
| 09:00 - 09:30 | Opening Overview: Amy Hurford |
| 09:30 - 09:40 | Introduction: Sumit Jyoti |
| 09:40 - 09:50 | Introduction: Ahsan Raquib |
| 09:50 - 11:00 | Small Group Work (CIHR project; CSF 2222 available) |
| 11:00 - 11:15 | Break |
| 11:15 - 11:25 | Introduction: Binod Shrestha |
| 11:25 - 11:35 | Introduction: James Watmough |
| 11:35 - 12:00 | Small Group Work (NFRF Explorations; CSF 2222 available) |
| 12:00 - 13:00 | Lunch |
| 13:00 - 13:30 | Talk: Jingyu Li |
| 13:30 - 13:40 | Introduction: Maheru Rahman |
| 13:40 - 13:50 | Introduction: Chunhua Ou |
| 13:50 - 14:45 | Small Group Work (ACCDMi year 1 report/year 2 planning; CSF 2222 available) |
| 14:45 - 15:00 | Break |
| 15:00 - 15:10 | Introduction: Danhan Hu |
| 15:10 - 15:20 | Introduction: Yuan Yuan |
| 15:20 - 16:00 | Daily Report Back |

### Day 2: Tuesday, July 28

| Time | Session |
|:---|:---|
| 09:00 - 09:30 | Morning Overview: Amy Hurford |
| 09:30 - 09:40 | Introduction: Joshua Mack |
| 09:40 - 09:50 | Introduction: Francis Anokye |
| 09:50 - 11:00 | Small Group Work (CIHR Project; CSF 2222 available) |
| 11:00 - 11:15 | Break |
| 11:15 - 11:25 | Introduction: JC Loredo-Osti |
| 11:25 - 11:35 | Introduction: Edward Susko (Online) |
| 11:35 - 12:00 | Small Group Work (NLHRF; CSF 2222 available) |
| 12:00 - 13:00 | Lunch |
| 13:00 - 13:30 | Talk: Abdou Fofana |
| 13:30 - 14:45 | Small Group Work (NFRF Explorations; CSF 2222 available) |
| 14:45 - 15:00 | Break |
| 15:00 - 15:10 | Introduction: Abdelmonem Mohamed (Online) |
| 15:10 - 15:20 | Introduction: Guanjie Lyu (Online) |
| 15:20 - 16:00 | Daily Report Back |

### Day 3: Wednesday, July 29

| Time | Session |
|:---|:---|
| 09:00 - 09:30 | Morning Overview: Amy Hurford |
| 09:30 - 11:00 | Small Group Work |
| 11:00 - 11:15 | Break |
| 11:15 - 12:00 | Small Group Work |
| 12:00 - 13:00 | Lunch |
| 13:00 - 14:45 | Small Group Work - Cater Andrews room not available |
| 14:45 - 15:00 | Break |
| 15:00 - 16:00 | Daily Report Back - Cater Andrews room not available|