---
title: "ACCDMi Newsletter - May 2026"
---

- We will have an in-person event at Memorial University. Dates I would like to consider for this are the late July/early August. Please complete the poll that was distributed via email to set the date for this event.

- The goal of the in-person meeting is to develop capacity in modelling using artificial intelligence. I would like for the group to start a collaborative project that demonstrates that we have the ability to apply modern tools. In the coming months, we will read papers that will help give us ideas for an appropriate collaborative project. Group members that have expertise in artificial intelligence should take leadership of suggesting readings and leading a discussion of them during online meetings prior to the in-person meeting in the summer. Please complete the poll that was distributed via email to set the timing of the online meetings.

- Financial support to attend the in-person meeting will be available for trainees and principal investigators at the AARMS institutions. 

- We will look to schedule online presentations from some of our members each month to become familar with their work.

- ACCDMi has a logo! Please use the [logo](https://ahurford.github.io/accdmi-website/logo.html) for your ACCDMi-related presentations.

- We have some preprints/publications in the last couple of months, which have been added to the website. If you have any ACCDMi-related publications, I would like to list these on the website. Please email Amy Hurford with information on any relevant publications.

Thanks again for your support of ACCDMi!